### PR TITLE
Use char array len instead of bytes

### LINKED ISSUE #5: Panic on multibyte utf string search
The following code panic at runtime (with git master fuse-rust):

```rust
fn main() {
    let pat = "f";
    let s = "®";

    let fuse = fuse_rust::Fuse::default();

    dbg!(fuse.search_text_in_string(pat, s));
}
```

Backtrace:

```
...
   2: core::panicking::panic_bounds_check
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:62
   3: <usize as core::slice::SliceIndex<[T]>>::index
             at /home/kitsu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3282
   4: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /home/kitsu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3123
   5: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /home/kitsu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2000
   6: fuse_rust::Fuse::search_util
             at ./src/lib.rs:288
   7: fuse_rust::Fuse::search
             at ./src/lib.rs:383
   8: fuse_rust::Fuse::search_text_in_string
             at ./src/lib.rs:450
...
```

### PR DESCRIPTION
**Pull request by l4l**
Apparently that was easier than I expected

resolves #5

### CODE REVIEW

**Comment by Blakeinstein** [comment]
Looks good to me! I really thought string length would match, Could you also add this as an example? So that it becomes a part of the test? I will merge the PR after that.

**Comment by l4l** [comment]
Yeah, sure. Maybe it's better add it as a (unit) test?

**Comment by Blakeinstein** [comment]
> Yeah, sure. Maybe it's better add it as a (unit) test?

Feel free to add it however you like. You can also change an existing example to include your case!

**Comment by Blakeinstein** [comment]
Uh, could you keep tests in a seperate file?

src/test.rs
```
use super::Fuse;

#[test]
fn multibyte_chars() {
    let pat = "f";
    let s = &[
        "®∮ℕ⊆ℕ₀⊂ℤℚ",
        "😊🥺😉😍😘😚",
        "⡍⠜⠇⠑⠹ ⠺⠁⠎",
        "გთხოვთ",
        "ıntəˈnæʃənəl",
        "γνωρίζω ἀπὸ",
        "コンニチハ",
    ];
    assert!(Fuse::default().search_text_in_iterable(pat, s.iter()).is_empty());
}
```

src/lib.rs
```
mod utils;
#[cfg(test)]
mod tests;
```

**Comment by l4l** [comment]
Yeah sure, in-placing is fairly common though. Anyway, maybe move it to the [tests folder](https://doc.rust-lang.org/book/ch11-03-test-organization.html#the-tests-directory) then?

**Comment by Blakeinstein** [comment]
> Yeah sure, in-placing is fairly common though. Anyway, maybe move it to the [tests folder](https://doc.rust-lang.org/book/ch11-03-test-organization.html#the-tests-directory) then?

Tests folder is for integration tests, as per rust book. Its just that having a test.rs separately, would make it a bit easier for looking at tests!

**Comment by Blakeinstein** [comment]
Thanks for your contribution! I will push a new release asap.

**Pull request merged**
